<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Mod.Notification.Spec</RootNamespace>
		<AssemblyName>FSH.Mod.Notification.Spec</AssemblyName>
		<NoWarn>$(NoWarn);S2094</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Lib\Shared\Shared.csproj" />
		<ProjectReference Include="..\..\..\Lib\Eventing.Abstractions\Eventing.Abstractions.csproj" />
	</ItemGroup>

</Project>
