<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Mods.Billing</RootNamespace>
		<AssemblyName>FSH.Mods.Billing</AssemblyName>
		<NoWarn>$(NoWarn);CA1031;CA1711;CA1812;CA1859;S3267</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Billing.Tests" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\Lib\Eventing\Eventing.csproj" />
	  <ProjectReference Include="..\..\..\Lib\Jobs\Jobs.csproj" />
	  <ProjectReference Include="..\..\..\Lib\Persistence\Persistence.csproj" />
	  <ProjectReference Include="..\..\..\Lib\Web\Web.csproj" />
	  <ProjectReference Include="..\Spec\Billing.Spec.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="QuestPDF" />
	</ItemGroup>

</Project>
