<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Mod.Chat</RootNamespace>
		<AssemblyName>FSH.Mod.Chat</AssemblyName>
		<NoWarn>$(NoWarn);CA1031;CA1812;CA1859;CA1002;CA2227;S3267</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Lib\Persistence\Persistence.csproj" />
		<ProjectReference Include="..\..\..\Lib\Web\Web.csproj" />
		<ProjectReference Include="..\..\..\Lib\Eventing\Eventing.csproj" />
		<ProjectReference Include="..\..\..\Lib\Storage\Storage.csproj" />
		<ProjectReference Include="..\Spec\Chat.Spec.csproj" />
		<ProjectReference Include="..\..\File\Spec\File.Spec.csproj" />
		<ProjectReference Include="..\..\Identity\Spec\Identity.Spec.csproj" />
	</ItemGroup>

</Project>
