<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Mod.File</RootNamespace>
		<AssemblyName>FSH.Mod.File</AssemblyName>
		<NoWarn>$(NoWarn);CA1031;CA1812;CA1859;CA1002;CA2227;S3267</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Lib\Persistence\Persistence.csproj" />
		<ProjectReference Include="..\..\..\Lib\Storage\Storage.csproj" />
		<ProjectReference Include="..\..\..\Lib\Web\Web.csproj" />
		<ProjectReference Include="..\..\..\Lib\Jobs\Jobs.csproj" />
		<ProjectReference Include="..\Spec\File.Spec.csproj" />
	</ItemGroup>

</Project>
