<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Mods.Notification</RootNamespace>
		<AssemblyName>FSH.Mods.Notification</AssemblyName>
		<NoWarn>$(NoWarn);CA1031;CA1711;CA1812;CA1859;CA1002;CA2227;S3267</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Lib\Persistence\Persistence.csproj" />
		<ProjectReference Include="..\..\..\Lib\Web\Web.csproj" />
		<ProjectReference Include="..\..\..\Lib\Eventing\Eventing.csproj" />
		<ProjectReference Include="..\..\..\Lib\Mailing\Mailing.csproj" />
		<ProjectReference Include="..\Spec\Notification.Spec.csproj" />
		<ProjectReference Include="..\..\Chat\Spec\Chat.Spec.csproj" />
		<ProjectReference Include="..\..\Billing\Spec\Billing.Spec.csproj" />
	</ItemGroup>

</Project>
