<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Mod.Audit.Spec</RootNamespace>
		<AssemblyName>FSH.Mod.Audit.Spec</AssemblyName>
		<NoWarn>$(NoWarn);S2094</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\..\Lib\Shared\Shared.csproj" />
	</ItemGroup>
</Project>
